# Builds deployment artifacts after PR to development is completed

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 
    npm install
    wasm-pack build
    npm run build
  displayName: 'npm install and build'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Anzu Artifacts'
    publishLocation: 'pipeline'